package com.mottc.patrol.data.source.local;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mottc.patrol.data.entity.Task;
import com.mottc.patrol.data.entity.ImageURL;

import com.mottc.patrol.data.source.local.TaskDao;
import com.mottc.patrol.data.source.local.ImageURLDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig taskDaoConfig;
    private final DaoConfig imageURLDaoConfig;

    private final TaskDao taskDao;
    private final ImageURLDao imageURLDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        imageURLDaoConfig = daoConfigMap.get(ImageURLDao.class).clone();
        imageURLDaoConfig.initIdentityScope(type);

        taskDao = new TaskDao(taskDaoConfig, this);
        imageURLDao = new ImageURLDao(imageURLDaoConfig, this);

        registerDao(Task.class, taskDao);
        registerDao(ImageURL.class, imageURLDao);
    }
    
    public void clear() {
        taskDaoConfig.clearIdentityScope();
        imageURLDaoConfig.clearIdentityScope();
    }

    public TaskDao getTaskDao() {
        return taskDao;
    }

    public ImageURLDao getImageURLDao() {
        return imageURLDao;
    }

}
